# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: UseDotNet@2
  displayName: Setup .NET
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: Restore dependencies
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: PowerShell@2
  displayName: Pulling docker image of SQL Server Express
  inputs:
    targetType: 'inline'
    script: 'docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Test@test123!" -e "MSSQL_PID=Express" -p 1435:1433 -d --name=sql mcr.microsoft.com/mssql/server:latest'
    pwsh: true

- task: PowerShell@2
  displayName: Checking docker image of SQL Server Express is running
  inputs:
    targetType: 'inline'
    script: 'docker ps'
    pwsh: true

- task: DotNetCoreCLI@2
  displayName: Running tests
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
